
Testing compiled code...
Database opened successfully

Dump
====
 Persons: 3 (is_empty = 0)
  1: Rémi 2
  2: Norbert 2
  3: Alexandre 1

 Cities: 2
  1: Paris
  2: Lille


Dump
====
 Persons: 0 (is_empty = 1)

 Cities: 0


Dump
====
 Persons: 3 (is_empty = 0)
  1: Toto 2
  2: Évariste 0
  3: Catherine 0

 Cities: 4
  1: Barcelona
  2: New York
  3: Paris
  4: Tokyo

first: 1: Barcelona
last: 4: Tokyo
Trying to update into a duplicate Paris: ...
city_by_name unique index failure: ("Paris") at id = 2 was already at id = 3

Dump
====
 Persons: 3 (is_empty = 0)
  1: Toto 2
  2: Évariste 0
  3: Catherine 0

 Cities: 4
  1: Barcelona
  2: New York
  3: Paris
  4: Tokyo


Validity + get_at:
Paris
0: invalid!
1: Barcelona
2: New York
3: invalid!
4: Tokyo
5: invalid!
6: invalid!
7: invalid!
8: invalid!
9: invalid!

Dump
====
 Persons: 5 (is_empty = 0)
  1: Toto 2
  2: Évariste 0
  3: Catherine 0
  4: Toto 4
  5: Toto 1

 Cities: 3
  1: Barcelona
  2: New York
  4: Tokyo

Finding all Totos:
 1: New York
 4: Tokyo
 5: Barcelona
No Totox in the database
(begin != end) = 1
empty = 0
count = 3
range.size() = 3
Found Catherine!
Found Catherine!
Comment allez-vous?
Sorting with explicit sort:
Albert
Catherine
Toto
Toto
Toto
Zoé
Évariste
Sorting with index:
Albert
Catherine
Toto
Toto
Toto
Zoé
Évariste
Reverse order of cities:
Washington
Tokyo
New York
Beijing
Barcelona
id in table_with_no_field: 1
W == B: 0
W != B: 1
W < B: 1
W <= B: 1
W > B: 0
W >= B: 0
B == B: 1
B != B: 0
B < B: 0
B <= B: 1
B > B: 0
B >= B: 1
Rémi
Norbert
Alexandre
Rémi
Norbert
Alexandre
